config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    # member do
    #  get :completed
    # end
    # resources :tasks do
    #   member do
    #     post :complete
    #   end
    # end
  end

  get     '/lists/:id/completed' => 'lists#show_completed', as: :completed_list
  delete  '/lists/:list_id/tasks/:id' => 'tasks#delete', as: :list_task
  post    '/lists/:list_id/tasks/:id/complete' => 'tasks#complete', as: :complete_list_task
  get     '/lists/:list_id/tasks' => 'tasks#index', as: :list_tasks
  post    '/lists/:list_id/tasks' => 'tasks#create'
  get     '/lists/:list_id/tasks/new' => 'tasks#new', as: :new_list_task
  # get   '/lists/:list_id/tasks/:id/edit' => 'tasks#edit', as: :edit_list_task
  # get   '/lists/:list_id/tasks/:id' =>  'tasks#show', as: :list_task
  patch   '/lists/:list_id/tasks/:id' => 'tasks#update'
  # put   '/lists/:list_id/tasks/:id' => 'tasks#update' #nesmie existovat
  # delete '/lists/:list_id/tasks/:id' => 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true

  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :name, :presence => true
  validates :list_id, :presence => true
  validates :priority, :presence => true, numericality: true

  default_scope { where('completed_at IS NULL AND deleted_at IS NULL') }
  default_scope { order(priority: :asc) }

  scope :completed, -> { where('completed_at IS NOT NULL AND deleted_at IS NULL') }
  scope :not_completed, -> { where('completed_at IS NULL AND deleted_at IS NULL') }
  scope :not_deleted, -> { where(:deleted_at => nil) }
  scope :deleted, -> { where("deleted_at IS NOT NULL") }
  scope :important, -> { where('priority < 0') }

  def completed?
    !completed_at.blank?
  end

  def deleted?
    !completed_at.blank?
    # !deleted_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :show_completed]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all.sort_by(&:name)
    set_important
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    if @list.update(list_params)
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.tasks.unscoped.where(list_id: @list.id).each(&:destroy)

    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end

  def show_completed
    # @tasks = @list.tasks
    @completed_tasks = @list.tasks.unscoped.where(list_id: @list.id).completed.sort_by(&:priority)

    render :show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  def set_important
    @important = []
    List.all.each do |list|
      @important.concat list.tasks.important
    end
    @important.sort_by!(&:priority)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, except: [:create, :new]

  def create
    @task = @list.tasks.create(task_params)
    if @task.save
      redirect_to @list, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def new
    @task = @list.tasks.new
  end

  def destroy
    @task.destroy
    redirect_to @list
  end

  def delete
    @task.update_attributes(deleted_at: Time.now)
    redirect_to @list, :notice => 'Task was successfully destroyed.'
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to @list # , notice: "Task completed"
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = @list.tasks.unscoped.find(params[:id])
  end

  def task_params
    params[:task].permit(:name, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <h1>
          My Awesome ToDo App
        </h1>
        <hr>
        <% if notice %>
          <div class="col-xs-12 alert alert-info">
            <%= notice %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="well">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div class="alert alert-danger">
      <% list.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <%= f.submit 'Save', class: 'btn btn-default' %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<% if @important.try(:any?) %>

<h2>Most important</h2>
<table id="most_important" class="table">
  <thead>
  <tr>
    <th>Task</th>
    <th>List</th>
    <th>Priority</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @important.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.list.name %></td>
      <td><%= task.priority %></td>
      <td><%= link_to 'Complete', complete_list_task_path(task.list, task), method: :post, class: 'btn btn-success' %></td>
      <td><%= link_to 'Remove', [task.list, task], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<% end %>

<h2>Lists <%= link_to 'New', new_list_path, class: 'btn btn-success' %></h2>

<table id="lists_table" class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Tasks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.description %></td>
        <td><%= list.tasks.count %></td>
        <td><%= link_to 'Show', list, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_list_path(list), class: 'btn btn-warning'  %></td>
        <td><%= link_to 'Remove', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div class="row text-center">
  <h2><%= @list.name %></h2>
  <p><%= @list.description %></p>
</div>

<%= link_to "New Task", new_list_task_path(@list), class: 'btn btn-success' %>
<% if action_name == 'show' %>
<%= link_to "View completed tasks", completed_list_path(@list), class: 'btn btn-default' %>
<% else %>
  <%= link_to "View tasks", @list, class: 'btn btn-default' %>
<% end %>

<table id="tasks_table" class="table">
  <tr>
    <th>Task</th>
    <th colspan="2"></th>
  </tr>
  <% (@completed_tasks || @list.tasks).each do |task| %>
  <tr>
    <td>
      <%= task.name %>
    </td>
    <td><%= task.deleted? ? '' : link_to('Complete', complete_list_task_path(@list, task), method: :post, class: 'btn btn-warning')  %></td>
    <td><%= link_to 'Remove', list_task_path(@list, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for [@list, task] do |f| %>
  <% if task.errors.any? %>
    <div class="alert alert-danger">
      <% task.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :priority %>
    <%= f.number_field :priority, class: 'form-control' %>
  </div>

  <%= f.submit 'Save', class: 'btn btn-default' %>
<% end %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', list_path(@list) %>